### ISSUE TITLE
errors during importing the data

### ISSUE THREAD

**Issue by zzzhxb** [NSGeophysics/GPRPy#2]
Hey Alain,
Thanks for the great work of open-sourse python tools for GPR processing. I have seen your AGU poster. And I have instralled the software, and import the example data. Then I tried to some other GSSI data, some errors occurs that "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 14: invalid continuation byte".  
So I write this issue and ask what types of GPR data are supported in GPRpy. Is there some extra requirmentes for the input data? How about the .Rad data?

**Comment by AlainPlattner** [comment]
Hi, 
Thanks for using gprpy. Currently, .dzt, .dt1, and ENVI standard BSQ data files are supported, but I'm happy to expand it to any other data format if you have an example file. What data file are you trying to load? For GSSI, I thought the file extension is usually .dzt.

Cheers

**Comment by AlainPlattner** [comment]
Hi Xuebing,
I just updated GPRPy and it can now also ready MALA data such as for example the RAMAC system. The MALA files have .rd3 and .rad endings, so perhaps this now works for you. Can you please install the new version of GPRPy and give it another try?
Thanks and best wishes,
Alain

**Comment by zzzhxb** [comment]
Hi Alain,
Thanks for the effort and time. I will re-install the new version. If I have any other questions, I will come back to you  .
Regards,
Xuebing

**Comment by zzzhxb** [comment]
> Hi Xuebing,
> I just updated GPRPy and it can now also ready MALA data such as for example the RAMAC system. The MALA files have .rd3 and .rad endings, so perhaps this now works for you. Can you please install the new version of GPRPy and give it another try?
> Thanks and best wishes,
> Alain

Hi Alain,
Thanks for the effort and time. I will re-install the new version. If I have any other questions, I will come back to you.
Regards,
Xuebing
