### ISSUE TITLE
GSSI Radargrams X axis incorrect

### ISSUE THREAD

**Issue by eshoemaker1** [NSGeophysics/GPRPy#21]
The x-axis is starting in the negatives instead of zero for GSSI files which is affecting locations of picks, observations, etc. Is there a way to rectify this?
![Screen Shot 2021-09-23 at 12 55 37 PM](https://user-images.githubusercontent.com/68022803/134575226-b013b409-2cf9-4014-9d1b-ca27066c8d79.png)

**Comment by AlainPlattner** [comment]
You can use the button "adj profile" to set the desired start and end x coordinates for your profile (and even to flip the profile left to right).
